export const tracking = {
    action: {
        download_curriculum_vitae: "download_curriculum_vitae",
        open_blog: "open_blog",
        open_github: "open_github",
        open_linkedin: "open_linkedin",
        send_mail: "send_email",
        open_medium: "open_medium",
        open_devto: "open_devto",
        open_twitter: "open_twitter",
        open_facebook: "open_facebook",
        open_instagram: "open_instagram",
        open_sclt_github: "open_sclt_github",
        open_sclt_thesis: "open_sclt_thesis",
        open_spectral_brdf_explorer_github: "open_spectral_brdf_explorer_github",
        open_id3tageditor_github: "open_id3tageditor_github",
        open_id3tageditor_doc: "open_id3tageditor_doc",
        open_mp3id3tagger_github: "open_mp3id3tagger_github",
        open_mp3id3tagger_dmg: "open_mp3id3tagger_dmg",
        open_rangeuislider_github: "open_rangeuislider_github",
        open_rangeuislider_doc: "open_rangeuislider_doc",
        open_tabbaruiaction_github: "open_tabbaruiaction_github",
        open_tabbaruiaction_doc: "open_tabbaruiaction_doc",
        open_home: "open_home",
        open_about_me: "open_about_me",
        open_art: "open_art",
        open_chat: "open_chat",
        open_mcp: "open_mcp",
        open_easter_egg_hunt: "open_easter_egg_hunt",
        open_contact: "open_contact",
        open_blog_archive: "open_blog_archive",
        open_blog_tags: "open_blog_tags",
        open_blog_authors: "open_blog_authors",
        open_blog_stats: "open_blog_stats",
        open_http_cookie_policy: "open_http_cookie_policy",
        reload: "reload",
        open_blog_post: "open_blog_post",
        open_blog_next_page: "open_blog_next_page",
        open_blog_previous_page: "open_blog_previous_page",
        open_blog_author: "open_blog_author",
        open_experience_and_education: "open_experience_and_education",
        open_blog_tag: "open_blog_tag",
        pull_to_refresh: "pull_to_refresh",
        red_pill: "red_pill",
        blue_pill: "blue_pill",
        open_down_arrow: "open_down_arrow",
        open_dsa_time_and_space_complexity: "open_dsa_time_and_space_complexity",
        open_dsa_roadmap: "open_dsa_roadmap",
        open_dsa_topic: "open_dsa_topic",
        open_dsa_exercises: "open_dsa_exercises",
        open_videogame_game: "open_videogame_game",
        open_videogame_console: "open_videogame_console",
        open_videogame_games: "open_videogame_games",
        open_videogame_collection: "open_videogame_collection",
        open_manga: "open_manga",
        open_manga_collection: "open_manga_collection",
        toggle_chrome_ai_features: "toggle_chrome_ai_features",
        chrome_ai_tldr: "chrome_ai_tldr",
        chrome_ai_key_points: "chrome_ai_key_points",
        open_chrome_ai_docs: "open_chrome_ai_docs",
        copy_code_block: "copy_code_block",
        pwa_install_prompt_shown: "pwa_install_prompt_shown",
        pwa_install_accepted: "pwa_install_accepted",
        pwa_install_dismissed: "pwa_install_dismissed",
        contact_queued_offline: "contact_queued_offline",
        contact_queue_replayed: "contact_queue_replayed",
        command_palette_open: "command_palette_open",
        command_palette_toggle_motion: "command_palette_toggle_motion",
        command_palette_open_chat: "command_palette_open_chat",
        command_palette_search_result_selected: "command_palette_search_result_selected",
        command_palette_open_matrix_rain_panel: "command_palette_open_matrix_rain_panel",
        command_palette_matrix_rain_preset_selected: "command_palette_matrix_rain_preset_selected",
        command_palette_open_easter_egg_hunt: "command_palette_open_easter_egg_hunt",
        command_palette_open_terminal: "command_palette_open_terminal",
        terminal_open: "terminal_open",
        easter_egg_hunt_reveal_hint: "easter_egg_hunt_reveal_hint",
        easter_egg_hunt_reveal_all: "easter_egg_hunt_reveal_all",
        easter_egg_hunt_reset: "easter_egg_hunt_reset",
        easter_egg_kung_fu: "easter_egg_kung_fu",
        easter_egg_spoon: "easter_egg_spoon",
        easter_egg_white_rabbit: "easter_egg_white_rabbit",
        easter_egg_the_choice: "easter_egg_the_choice",
        easter_egg_the_one: "easter_egg_the_one",
        easter_egg_dodge_this: "easter_egg_dodge_this",
        open_chicio_labs: "open_chicio_labs",
        open_matrix_rain_webgpu: "open_matrix_rain_webgpu",
        open_matrix_rain_webgpu_demo: "open_matrix_rain_webgpu_demo",
        open_matrix_rain_webgpu_github: "open_matrix_rain_webgpu_github",
        open_react_native_skia_skeleton_github: "open_react_native_skia_skeleton_github",
    },
    category: {
        home: "home",
        contact: "contact",
        blog_home: "blog_home",
        blog_archive: "blog_archive",
        blog_post: "blog_post",
        blog_tags: "blog_tags",
        blog_tag: "blog_tags",
        blog_authors: "blog_authors",
        blog_stats: "blog_stats",
        blog_author: "blog_author",
        blog_search: "blog_search",
        cookie_policy: "cookie_policy",
        privacy_policy: "privacy_policy",
        notfound: "notfound",
        art: "art",
        data_structures_and_algorithms: "data_structures_and_algorithms",
        videogames: "videogames",
        manga: "manga",
        chat: "chat",
        mcp: "mcp",
        about_me: "about_me",
        easter_egg_hunt: "easter_egg_hunt",
        clowns: "clowns",
        pwa: "pwa",
        command_palette: "command_palette",
        terminal: "terminal",
    },
    label: {
        footer: "footer",
        body: "body",
        header: "header",
    },
};

export interface TrackingData {
    category: string;
    label: string | undefined;
    action: string;
}

export type TrackingPayload = { event_category: string; event_label: string | undefined };

declare global {
    interface Window {
        gtag: (event: "event", action: string, payload: TrackingPayload) => void;
    }
}
